"""Markdown integration brief. Exports even when work is unresolved, but says so prominently."""

from __future__ import annotations

from models import APPROVED, MappingEvaluation, now_utc
from review import STATUS_ICONS, Workspace, build_test_plan, readiness, risk_sorted, rule_questions
from transformations import REGISTRY

LIMITATIONS = [
    "Prototype built for an interview demonstration. All organisations, requirements and data are fictional.",
    "Not an Experian product; it has no access to Experian systems and has not been tested against Experian data.",
    "It prepares and validates data mappings only. It makes no lending or credit decisions.",
    "State lives in one browser session. There is no authentication, and the reviewer is a fixed 'Demo reviewer'.",
    "Only .txt requirements and .csv dictionaries are supported. Requirement identifiers are detected by an 'R1:'-style pattern.",
    "Semantic checks (gross/net, submission time, units) use keyword and unit-string heuristics. They catch the known "
    "failure modes in the sample but are not exhaustive.",
    "Checks run against a single sample value per field, not a representative dataset.",
    "Demo mode replays a saved proposal for the fictional sample. Other files need live AI or manual correction.",
]


def _cell(value: object) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ").strip() or "—"


def _table(headers: list[str], rows: list[list[object]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(_cell(v) for v in row) + " |" for row in rows]
    return "\n".join(lines)


def _status(status: str) -> str:
    return f"{STATUS_ICONS.get(status, '')} {status}".strip()


def _sources(fields: list[str]) -> str:
    return ", ".join(f"`{f}`" for f in fields) if fields else "_none identified_"


def build_brief(ws: Workspace, evaluations: dict[str, MappingEvaluation] | None = None) -> str:
    evaluations = evaluations or ws.evaluate()
    ordered = risk_sorted(ws, evaluations)
    ready, headline = readiness(ws, evaluations)
    approved = [m for m in ordered if evaluations[m.target_field].status == APPROVED]
    unapproved = [m for m in ordered if evaluations[m.target_field].status != APPROVED]
    out: list[str] = []

    out.append(f"# Integration brief: {ws.customer}")
    out.append("")
    out.append(f"Generated by FieldBridge: Integration Readiness Workbench (prototype) on {now_utc():%Y-%m-%d %H:%M UTC}.")
    out.append("")
    if ready:
        out.append(f"> **✔ READY FOR BUILD.** {headline}")
    else:
        out.append(f"> **⚠ NOT READY FOR BUILD.** {headline}")
        out.append(">")
        out.append("> Do not implement the unapproved mappings below until the open questions are answered and a reviewer approves them.")
    out.append("")

    out.append("## 1. Project summary")
    out.append("")
    out.append(f"- **Customer:** {ws.customer}")
    out.append(f"- **Objective:** {ws.objective}")
    out.append(f"- **Mapping proposals from:** {ws.mapping_source}")
    out.append(f"- **Required target fields:** {len(ws.targets)} ({len(approved)} approved, {len(unapproved)} unapproved)")
    out.append("- **Principle:** AI interprets requirements and proposes mappings; deterministic code performs checks and "
               "transformations; a person makes the final decision.")
    out.append("")

    out.append("## 2. Input files")
    out.append("")
    out.append(_table(["File", "Type", "Origin", "Detected", "Parse status"],
                      [[f.name, f.file_type, f.origin, f.count, f.status] for f in ws.input_files]))
    out.append("")

    out.append("## 3. Approved mappings")
    out.append("")
    if approved:
        out.append(_table(["Target field", "Source field(s)", "Transformation", "Requirement", "Approved at"],
                          [[f"`{m.target_field}`", _sources(m.source_fields), f"`{m.transformation_id}`", m.requirement_id,
                            m.decided_at.strftime("%Y-%m-%d %H:%M:%S UTC") if m.decided_at else ""] for m in approved]))
    else:
        out.append("_No mappings have been approved._")
    out.append("")

    out.append("## 4. Unapproved mappings")
    out.append("")
    if unapproved:
        out.append(_table(["Target field", "Source field(s)", "Transformation", "Status", "Decision", "Why"],
                          [[f"`{m.target_field}`", _sources(m.source_fields), f"`{m.transformation_id}`",
                            _status(evaluations[m.target_field].status), m.decision,
                            "; ".join(evaluations[m.target_field].reasons)] for m in unapproved]))
    else:
        out.append("_None. Every required mapping is approved._")
    out.append("")

    out.append("## 5. Transformation formulas")
    out.append("")
    used = {m.transformation_id for m in ws.mappings}
    rows = []
    for tid in used:
        spec = REGISTRY.get(tid)
        applied = ", ".join(f"`{m.target_field}`" for m in ws.mappings if m.transformation_id == tid)
        rows.append([f"`{tid}`", spec.formula if spec else "NOT IN APPROVED REGISTRY", applied])
    out.append(_table(["Transformation", "Formula (trusted code)", "Applied to"], sorted(rows)))
    out.append("")

    out.append("## 6. Requirement evidence")
    out.append("")
    for m in ordered:
        check = next(c for c in evaluations[m.target_field].checks if c.number == 5)
        verified = "verified verbatim" if check.status == "Ready" else f"NOT VERIFIED ({check.evidence})"
        out.append(f"**`{m.target_field}`** ← {m.requirement_id or 'no requirement cited'} ({verified})")
        out.append("")
        out.append(f"> {m.evidence_quote or '(no evidence quoted)'}")
        out.append("")

    out.append("## 7. Assumptions")
    out.append("")
    any_assumption = False
    for m in ordered:
        spec = REGISTRY.get(m.transformation_id)
        items = [f"{a} _(proposal)_" for a in m.assumptions] + [f"{a} _(transformation registry)_" for a in (spec.assumptions if spec else ())]
        if items:
            any_assumption = True
            confirmed = " (confirmed by approval)" if evaluations[m.target_field].status == APPROVED else " (unconfirmed)"
            out.append(f"- **`{m.target_field}`**{confirmed}")
            out.extend(f"  - {a}" for a in items)
    if not any_assumption:
        out.append("_No assumptions recorded._")
    out.append("")

    out.append("## 8. Readiness-check results")
    out.append("")
    for m in ordered:
        ev = evaluations[m.target_field]
        out.append(f"### `{m.target_field}`: {_status(ev.status)}")
        out.append("")
        out.append(_table(["#", "Check", "Status", "Evidence used", "Remediation"],
                          [[c.number, c.name, _status(c.status), c.evidence, c.remediation] for c in ev.checks]))
        out.append("")

    out.append("## 9. Open questions")
    out.append("")
    derived = rule_questions(ws, evaluations)
    open_items = [q for q in ws.open_questions if not q.resolved]
    resolved = [q for q in ws.open_questions if q.resolved]
    if not (derived or open_items or resolved):
        out.append("_No open questions._")
    for q in open_items:
        out.append(f"- [ ] **OPEN:** {q.text} _(raised by {q.raised_by})_")
    for text in derived:
        out.append(f"- [ ] **OPEN:** {text} _(raised by rule checks)_")
    for q in resolved:
        out.append(f"- [x] Resolved: {q.text} _(raised by {q.raised_by})_")
    out.append("")

    out.append("## 10. Initial test plan")
    out.append("")
    out.append("Generated from deterministic templates attached to each approved transformation.")
    out.append("")
    plan = build_test_plan(ws)
    out.append(_table(["ID", "Target field", "Case", "Given", "Expect"],
                      [[f"T{i}", f"`{r['Target']}`", r["Case"], r["Given"], r["Expect"]] for i, r in enumerate(plan, start=1)]))
    out.append("")

    out.append("## 11. Audit history")
    out.append("")
    out.append(_table(["Timestamp (UTC)", "Actor", "Action", "Target field", "Previous value", "New value"],
                      [[e.timestamp.strftime("%Y-%m-%d %H:%M:%S"), e.actor, e.action, e.target_field, e.previous_value, e.new_value]
                       for e in ws.audit]))
    out.append("")

    out.append("## 12. Prototype limitations")
    out.append("")
    out.extend(f"- {item}" for item in LIMITATIONS)
    out.append("")
    return "\n".join(out)
