/** Markdown integration brief. Exports even when work is unresolved, but says so prominently. */

import { APPROVED, READY, type MappingStatus } from "./models";
import {
  buildTestPlan,
  evaluateAll,
  readiness,
  riskSorted,
  ruleQuestions,
  type Evaluations,
  type Workspace,
} from "./review";
import { findSpec } from "./transformations";

export const STATUS_ICONS: Record<MappingStatus, string> = {
  Ready: "✓",
  "Review required": "!",
  Missing: "○",
  Blocked: "✕",
  Approved: "✔",
};

export const LIMITATIONS = [
  "Prototype built for an interview demonstration. Every organisation, requirement and record is demo data, not real data.",
  "Not an Experian product; it has no access to Experian systems and has not been tested against Experian data.",
  "It prepares and validates data mappings only. It makes no lending or credit decisions.",
  "State lives in one browser tab. There is no authentication, and the reviewer is a fixed 'Demo reviewer'.",
  "Only .txt requirements and .csv dictionaries are supported. Requirement identifiers are detected by an 'R1:'-style pattern.",
  "Semantic checks (gross/net, submission time, units) use keyword and unit-string heuristics. They catch the known " +
    "failure modes in the demo data but are not exhaustive.",
  "Checks run against a single sample value per field, not a representative dataset.",
  "Demo mode replays a saved proposal for the demo data. Other files need live AI or manual correction.",
];

function cell(value: unknown): string {
  const text = value === null || value === undefined ? "" : String(value);
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ").trim() || "—";
}

function table(headers: string[], rows: unknown[][]): string {
  return [
    `| ${headers.join(" | ")} |`,
    `|${"---|".repeat(headers.length)}`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ].join("\n");
}

const status = (s: MappingStatus) => `${STATUS_ICONS[s]} ${s}`;
const sources = (fields: string[]) => (fields.length ? fields.map((f) => `\`${f}\``).join(", ") : "_none identified_");
const stamp = (iso: string) => iso.replace("T", " ").replace("Z", " UTC");

export function briefFileName(ws: Workspace): string {
  return `fieldbridge_brief_northstar_${ws.createdAt.slice(0, 10).replace(/-/g, "")}.md`;
}

export function buildBrief(ws: Workspace, evaluations: Evaluations = evaluateAll(ws)): string {
  const ordered = riskSorted(ws, evaluations);
  const { ready, headline } = readiness(ws, evaluations);
  const approved = ordered.filter((m) => evaluations[m.target_field].status === APPROVED);
  const unapproved = ordered.filter((m) => evaluations[m.target_field].status !== APPROVED);
  const out: string[] = [];
  const push = (...lines: string[]) => out.push(...lines);

  push(`# Integration brief: ${ws.customer} (demo data)`, "");
  push(`Generated by FieldBridge: Integration Readiness Workbench (prototype) on ${stamp(new Date().toISOString().slice(0, 16) + "Z")}.`, "");
  if (ready) {
    push(`> **✔ READY FOR BUILD.** ${headline}`, "");
  } else {
    push(
      `> **⚠ NOT READY FOR BUILD.** ${headline}`,
      ">",
      "> Do not implement the unapproved mappings below until the open questions are answered and a reviewer approves them.",
      "",
    );
  }

  push("## 1. Project summary", "");
  push(
    `- **Customer:** ${ws.customer} (demo data)`,
    `- **Objective:** ${ws.objective}`,
    `- **Mapping proposals from:** ${ws.mappingSource}`,
    `- **Required target fields:** ${ws.targets.length} (${approved.length} approved, ${unapproved.length} unapproved)`,
    "- **Principle:** AI interprets requirements and proposes mappings; deterministic code performs checks and " +
      "transformations; a person makes the final decision.",
    "",
  );

  push("## 2. Input files", "");
  push(table(["File", "Type", "Origin", "Detected", "Parse status"], ws.inputFiles.map((f) => [f.name, f.fileType, f.origin, f.count, f.status])), "");

  push("## 3. Approved mappings", "");
  push(
    approved.length
      ? table(
          ["Target field", "Source field(s)", "Transformation", "Requirement", "Approved at"],
          approved.map((m) => [`\`${m.target_field}\``, sources(m.source_fields), `\`${m.transformation_id}\``, m.requirement_id, m.decided_at ? stamp(m.decided_at) : ""]),
        )
      : "_No mappings have been approved._",
    "",
  );

  push("## 4. Unapproved mappings", "");
  push(
    unapproved.length
      ? table(
          ["Target field", "Source field(s)", "Transformation", "Status", "Decision", "Why"],
          unapproved.map((m) => [
            `\`${m.target_field}\``,
            sources(m.source_fields),
            `\`${m.transformation_id}\``,
            status(evaluations[m.target_field].status),
            m.decision,
            evaluations[m.target_field].reasons.join("; "),
          ]),
        )
      : "_None. Every required mapping is approved._",
    "",
  );

  push("## 5. Transformation formulas", "");
  const used = [...new Set(ws.mappings.map((m) => m.transformation_id))].sort();
  push(
    table(
      ["Transformation", "Formula (trusted code)", "Applied to"],
      used.map((tid) => [
        `\`${tid}\``,
        findSpec(tid)?.formula ?? "NOT IN APPROVED REGISTRY",
        ws.mappings.filter((m) => m.transformation_id === tid).map((m) => `\`${m.target_field}\``).join(", "),
      ]),
    ),
    "",
  );

  push("## 6. Requirement evidence", "");
  for (const m of ordered) {
    const check = evaluations[m.target_field].checks.find((c) => c.number === 5)!;
    const verified = check.status === READY ? "verified verbatim" : `NOT VERIFIED (${check.evidence})`;
    push(`**\`${m.target_field}\`** ← ${m.requirement_id || "no requirement cited"} (${verified})`, "", `> ${m.evidence_quote || "(no evidence quoted)"}`, "");
  }

  push("## 7. Assumptions", "");
  let anyAssumption = false;
  for (const m of ordered) {
    const spec = findSpec(m.transformation_id);
    const items = [...m.assumptions.map((a) => `${a} _(proposal)_`), ...(spec?.assumptions ?? []).map((a) => `${a} _(transformation registry)_`)];
    if (!items.length) continue;
    anyAssumption = true;
    const confirmed = evaluations[m.target_field].status === APPROVED ? " (confirmed by approval)" : " (unconfirmed)";
    push(`- **\`${m.target_field}\`**${confirmed}`, ...items.map((a) => `  - ${a}`));
  }
  if (!anyAssumption) push("_No assumptions recorded._");
  push("");

  push("## 8. Readiness-check results", "");
  for (const m of ordered) {
    const ev = evaluations[m.target_field];
    push(`### \`${m.target_field}\`: ${status(ev.status)}`, "");
    push(table(["#", "Check", "Status", "Evidence used", "Remediation"], ev.checks.map((c) => [c.number, c.name, status(c.status), c.evidence, c.remediation])), "");
  }

  push("## 9. Open questions", "");
  const derived = ruleQuestions(ws, evaluations);
  const openItems = ws.openQuestions.filter((q) => !q.resolved);
  const resolved = ws.openQuestions.filter((q) => q.resolved);
  if (!derived.length && !openItems.length && !resolved.length) push("_No open questions._");
  for (const q of openItems) push(`- [ ] **OPEN:** ${q.text} _(raised by ${q.raised_by})_`);
  for (const q of derived) push(`- [ ] **OPEN:** ${q.text} _(raised by rule checks)_`);
  for (const q of resolved) push(`- [x] Resolved: ${q.text} _(raised by ${q.raised_by})_`);
  push("");

  push("## 10. Initial test plan", "", "Generated from deterministic templates attached to each approved transformation.", "");
  push(
    table(
      ["ID", "Target field", "Case", "Given", "Expect"],
      buildTestPlan(ws).map((r, i) => [`T${i + 1}`, `\`${r.target}\``, r.case, r.given, r.expect]),
    ),
    "",
  );

  push("## 11. Audit history", "");
  push(
    table(
      ["Timestamp (UTC)", "Actor", "Action", "Target field", "Previous value", "New value"],
      ws.audit.map((e) => [e.timestamp.replace("T", " ").replace("Z", ""), e.actor, e.action, e.target_field, e.previous_value, e.new_value]),
    ),
    "",
  );

  push("## 12. Prototype limitations", "", ...LIMITATIONS.map((item) => `- ${item}`), "");
  return out.join("\n");
}
